# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/sk/Desktop/SparseL1Attention/AttentionCore/AttentionCore.srcs/sources_1/ip/Q/Q.xci
# IP: The module: 'Q' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sk/Desktop/SparseL1Attention/AttentionCore/AttentionCore.gen/sources_1/ip/Q/Q_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Q'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/sk/Desktop/SparseL1Attention/AttentionCore/AttentionCore.srcs/sources_1/ip/Q/Q.xci
# IP: The module: 'Q' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sk/Desktop/SparseL1Attention/AttentionCore/AttentionCore.gen/sources_1/ip/Q/Q_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Q'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
