#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2023.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sun Jan 25 16:39:23 IST 2026
# SW Build 4029153 on Fri Oct 13 20:13:54 MDT 2023
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_AttentionCore_behav -key {Behavioral:sim_1:Functional:tb_AttentionCore} -tclbatch tb_AttentionCore.tcl -view /home/sk/Desktop/SparseL1Attention/AttentionCore/tb_AttentionCore_behav.wcfg -log simulate.log"
xsim tb_AttentionCore_behav -key {Behavioral:sim_1:Functional:tb_AttentionCore} -tclbatch tb_AttentionCore.tcl -view /home/sk/Desktop/SparseL1Attention/AttentionCore/tb_AttentionCore_behav.wcfg -log simulate.log

