# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/sk/Desktop/SparseL1Attention/AttentionCore/AttentionCore.srcs/sources_1/ip/EXP/EXP.xci
# IP: The module: 'EXP' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sk/Desktop/SparseL1Attention/AttentionCore/AttentionCore.gen/sources_1/ip/EXP/EXP_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'EXP'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/sk/Desktop/SparseL1Attention/AttentionCore/AttentionCore.srcs/sources_1/ip/EXP/EXP.xci
# IP: The module: 'EXP' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sk/Desktop/SparseL1Attention/AttentionCore/AttentionCore.gen/sources_1/ip/EXP/EXP_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'EXP'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
